#pragma once

// HiFTGenerator — neural vocoder that turns 80-mel @ 50 Hz into 24 kHz
// PCM. The last S3Gen component. Lives under flow.* peers as
// `mel2wav.*` in the chatterbox_s3gen GGUF.
//
// Architecture (Turbo defaults: upsample_rates=[8,5,3],
// upsample_kernel_sizes=[16,11,7], resblock_kernel_sizes=[3,7,11],
// source_resblock_kernel_sizes=[7,7,11], nb_harmonics=8, n_fft=16,
// hop_len=4):
//
//   mel (1, 80, T_mel)
//      |--> F0 predictor (5x Conv1d k=3 + ELU + Linear -> abs)
//      |        -> f0 (1, T_mel)
//      |        nearest-upsample by 480 (= 8*5*3*4)
//      |        -> NSF source (SineGen 8 harmonics + noise + tanh-Linear merge)
//      |        -> source (1, 1, T_mel * 480)
//      |        -> STFT(n_fft=16, hop=4) -> s_stft (1, 18, T_stft)
//      v
//   conv_pre (Conv1d 80->512, k=7, p=3)
//   for i in 0..2:
//     leaky_relu(0.1) -> ups[i] (ConvT1d) -> [+ reflection_pad(1, 0) if i==2]
//     -> + source_resblock[i](source_downs[i](s_stft))
//     -> mean of 3 parallel ResBlocks (kernel = resblock_kernels[i])
//   leaky_relu -> conv_post (Conv1d 64->18, k=7, p=3)
//   magnitude = exp(x[:9]),  phase = sin(x[9:])
//   wav = iSTFT(magnitude, phase, n_fft=16, hop=4)
//   wav = clamp(wav, -0.99, 0.99)
//
// All convs in this module use weight_norm parametrization
// (g, v -> w = g * v / ||v||). We pre-combine at load time and stash
// the fused weights in a separate context.
//
// ResBlock = 3x (Snake -> Conv k=K d=d_i -> Snake -> Conv k=K d=1 -> +x).
// Snake activation: y = x + (1/(alpha + eps)) * sin^2(x * alpha), alpha
// is a learned (C,) parameter per Snake instance. We pre-combine
// (alpha, inv_alpha) at load time.
//
// Reference oracle: scripts/reference_hift_vocoder.py. Survey:
// docs/s3gen-survey.md Component 6.

#include "model.h"

#include <cstdint>
#include <memory>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

struct ggml_backend;
typedef ggml_backend* ggml_backend_t;
struct ggml_backend_buffer;
typedef ggml_backend_buffer* ggml_backend_buffer_t;
struct ggml_context;
struct ggml_tensor;

namespace chatterbox {

struct HiFTConfig {
    int32_t in_channels       = 80;
    int32_t base_channels     = 512;
    int32_t n_fft             = 16;
    int32_t hop_len           = 4;
    int32_t sampling_rate     = 24000;
    int32_t nb_harmonics      = 8;        // 9 channels total
    int32_t upsample_factor   = 480;      // 8 * 5 * 3 * 4
    int32_t n_upsamples       = 3;
    int32_t n_kernels         = 3;        // ResBlock parallel kernels per stage
    float   lrelu_slope       = 0.1f;
    float   audio_limit       = 0.99f;
    float   snake_eps         = 1e-9f;

    // Stage 0/1/2 channels: 256, 128, 64 (= base / 2^(i+1)).
    // Upsample strides and kernel sizes:
    int32_t up_strides[3]     = {8, 5, 3};
    int32_t up_kernels[3]     = {16, 11, 7};
    int32_t resblock_kernels[3] = {3, 7, 11};
    int32_t src_strides[3]     = {15, 3, 1};     // from cumulative downsample
    int32_t src_kernels[3]     = {7, 7, 11};
};

class HiFTVocoder {
public:
    static std::unique_ptr<HiFTVocoder> load(Model* s3gen_model);

    ~HiFTVocoder();
    HiFTVocoder(const HiFTVocoder&) = delete;
    HiFTVocoder& operator=(const HiFTVocoder&) = delete;

    const HiFTConfig& config() const { return cfg_; }

    // F0 predictor: in-graph. mel (T_mel, 80) row-major -> f0 (T_mel,).
    std::vector<float> predict_f0(const std::vector<float>& mel, int T_mel);

    // NSF source generator: f0 @ 50 Hz -> source signal @ 24 kHz.
    //
    //   f0          (T_mel,)                          input fundamental
    //                                                  frequencies in Hz
    //   phase_vec   (n_harmonics + 1,) optional        if non-empty, used
    //                                                  in place of an
    //                                                  internal uniform[-π,π]
    //                                                  draw (index 0 is
    //                                                  ALWAYS overridden
    //                                                  to 0 by SineGen)
    //   noise_z     ((n_harmonics+1) * T_wav,) optional standard-normal
    //                                                  noise; if empty
    //                                                  generated by an
    //                                                  internal std::mt19937
    //   seed        used only when the optional inputs are empty
    //
    // Returns: source (T_wav,) in [-1, 1], where T_wav = T_mel * 480.
    std::vector<float> generate_source(
        const std::vector<float>& f0,
        const std::vector<float>& phase_vec = {},
        const std::vector<float>& noise_z   = {},
        uint64_t                  seed       = 7);

    // Decode: mel + precomputed source signal -> 24 kHz waveform.
    //
    // mel:    (T_mel, 80) row-major
    // source: (T_wav,) — NSF source generated host-side from f0 (the
    //         caller passes this in for deterministic parity)
    //
    // Returns wav (T_wav,) PCM fp32 in [-0.99, +0.99].
    std::vector<float> decode(const std::vector<float>& mel, int T_mel,
                                const std::vector<float>& source, int T_wav);

    // Stage-keyed decode for bisect-debug. Same args as `decode`,
    // but also returns intermediates keyed by the stage names produced
    // by reference_hift_vocoder.py.
    std::vector<float> decode_with_stages(
        const std::vector<float>& mel, int T_mel,
        const std::vector<float>& source, int T_wav,
        std::unordered_map<std::string, std::vector<float>>& stages_out,
        std::unordered_map<std::string, std::pair<int, int>>& stage_shapes);

    // ---- Internal weight bundles (public for the test harness to peek) ----

    // A single Conv1d weight bundle (fused: w = g*v/||v||).
    struct ConvW {
        ggml_tensor* w = nullptr;     // (K, C_in, C_out) ggml ne, fp16 fused
        ggml_tensor* b = nullptr;     // (C_out,) fp32
    };

    struct ResBlock {
        // For each of 3 (kernel_size, dilation) pairs:
        struct Sublayer {
            ConvW         conv1, conv2;
            ggml_tensor*  alpha1_inv = nullptr;   // (C,) precomputed 1/(α+ε)
            ggml_tensor*  alpha1     = nullptr;   // (C,) raw α
            ggml_tensor*  alpha2_inv = nullptr;
            ggml_tensor*  alpha2     = nullptr;
        };
        std::vector<Sublayer> sublayers;   // 3 of these
        int kernel_size = 0;
    };

private:
    HiFTVocoder() = default;

    bool fetch_(Model* m);

    HiFTConfig       cfg_;
    Model*           model_   = nullptr;
    ggml_backend_t   backend_ = nullptr;

    // Derived (precombined) weights.
    ggml_context*         deriv_ctx_     = nullptr;
    ggml_backend_buffer_t deriv_buffer_  = nullptr;

    // Top-level
    ConvW                conv_pre_;
    ConvW                conv_post_;
    std::vector<ConvW>   ups_;           // 3
    std::vector<ConvW>   source_downs_;  // 3 (NOT weight-normed; plain conv)
    std::vector<ResBlock> source_resblocks_;  // 3
    std::vector<ResBlock> resblocks_;          // 9 (3 per upsample stage)

    // F0 predictor (5 condnet convs + classifier Linear).
    std::vector<ConvW>   f0_condnet_;    // 5
    ggml_tensor*         f0_cls_w_ = nullptr;
    ggml_tensor*         f0_cls_b_ = nullptr;

    // m_source.l_linear (Linear 9 -> 1) — owned by reference path; not
    // used by the in-graph decode (source is host-precomputed).
    ggml_tensor*         m_src_w_ = nullptr;
    ggml_tensor*         m_src_b_ = nullptr;

    // STFT/iSTFT support (Hann window, n_fft samples, fp32).
    std::vector<float>   hann_window_;
};

}  // namespace chatterbox
