"""Drive the web UI like a user and capture proof artifacts.

Run against a running server: python scripts/ui_walkthrough.py [base_url]
Saves: /tmp/ui_home.png, /tmp/ui_result.png, and the generated audio.
"""
import sys, os
try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass
from playwright.sync_api import sync_playwright

BASE = sys.argv[1] if len(sys.argv) > 1 else "http://127.0.0.1:8087"
REF_WAV = os.path.abspath("voices/Olivia.wav")

with sync_playwright() as p:
    b = p.chromium.launch(args=["--autoplay-policy=no-user-gesture-required"])
    pg = b.new_page()
    errs = []
    pg.on("pageerror", lambda e: errs.append(str(e)))
    pg.goto(BASE, wait_until="networkidle")
    pg.wait_for_timeout(1500)
    pg.screenshot(path="/tmp/ui_home.png", full_page=True)
    # Expand the Advanced <details> so its controls are interactable.
    pg.evaluate("() => document.querySelectorAll('details').forEach(d => d.open = true)")
    pg.wait_for_timeout(200)

    fmts = pg.eval_on_selector_all("#format option", "els=>els.map(e=>e.textContent)")
    voices = pg.eval_on_selector_all("#voice option", "els=>els.map(e=>e.textContent)")
    print(f"voices in dropdown: {len(voices)}; formats: {fmts}")

    # 1) Pick a voice, type, choose MP3, generate.
    pg.select_option("#voice", "Gianna")
    pg.fill("#text", "Trying the Chatterbox web UI from the Docker image.")
    pg.select_option("#format", "mp3")
    pg.click("button:has-text('Generate')")
    pg.wait_for_selector("audio[src^='blob:']", timeout=90000)
    href = pg.get_attribute("a[role='button']:has-text('Download')", "href")
    dl_name = pg.get_attribute("a[role='button']:has-text('Download')", "download")
    print(f"generated (mp3): download name = {dl_name}, blob = {href[:24]}...")
    pg.screenshot(path="/tmp/ui_result.png", full_page=True)

    # Pull the generated bytes out of the blob to prove it's real audio.
    b64 = pg.evaluate(
        """async () => {
            const a = document.querySelector("a[role='button']");
            const blob = await (await fetch(a.href)).blob();
            const buf = new Uint8Array(await blob.arrayBuffer());
            return { len: buf.length, head: Array.from(buf.slice(0,3)) };
        }"""
    )
    print(f"mp3 blob: {b64['len']} bytes, head={b64['head']} "
          f"({'frame-sync OK' if b64['head'][0]==255 or b64['head']==[73,68,51] else 'check'})")

    # 2) History should now have an entry.
    hist = pg.eval_on_selector_all("ul.history li", "els=>els.length")
    print(f"history entries: {hist}")

    # 3) Voice cloning from an uploaded reference WAV.
    pg.set_input_files("input[type=file]", REF_WAV)
    pg.click("button:has-text('Upload & clone')")
    pg.wait_for_function(
        "() => Alpine.$data(document.querySelector('main')).useClone === true",
        timeout=60000,
    )
    clone_status = pg.eval_on_selector("fieldset small", "el=>el.textContent")
    print(f"clone: useClone=True, status='{clone_status.strip()}'")
    # Generate with the cloned voice.
    pg.fill("#text", "This line uses the cloned voice.")
    pg.select_option("#format", "wav")
    pg.click("button:has-text('Generate')")
    pg.wait_for_selector("audio[src^='blob:']", timeout=90000)
    print("generated with cloned voice: OK")

    # 4) Streaming.
    pg.evaluate("() => Alpine.$data(document.querySelector('main')).useLibraryVoice()")
    pg.select_option("#voice", "Miles")
    pg.evaluate("() => { Alpine.$data(document.querySelector('main')).stream = true; }")
    pg.fill("#text", "Streaming smoke. Second sentence here.")
    pg.click("button:has-text('Generate')")
    pg.wait_for_function(
        "() => Alpine.$data(document.querySelector('main')).streamSamples > 0",
        timeout=90000,
    )
    samp = pg.evaluate("() => Alpine.$data(document.querySelector('main')).streamSamples")
    print(f"streamed PCM samples: {samp} (~{samp/24000:.1f}s)")

    print("PAGE ERRORS:", errs or "none")
    b.close()
    print("RESULT:", "PASS" if not errs else "FAIL")
